name: evently
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1
  intl: any
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.4.7
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#F4F7FF"
  image: assets/images/Evently.png
  branding: assets/images/route.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/evently_splash2.png
    icon_background_color: "#F4F7FF"
    branding: assets/images/route.png



flutter:


  uses-material-design: true

  generate: true


  assets:
    - assets/images/

